openapi: 3.0.0
info:
  title: lambda-express-sequelize
  description: documentación lambda-express-sequelize
  version: 1.0.0
  servers:
    - http://localhost:4000
paths:
  /api/User:
    get:
      tags:
        - User
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties: {}
                example: null
    post:
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: {}
              example: &ref_0
                uuid: 520d1ddd-e0a7-4ddc-8c25-c187d3e4f338
                nombre: Esteban Quintero
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties: {}
                example: *ref_0
  /api/User/:uuid:
    put:
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: {}
              example: &ref_1
                uuid: 520d1ddd-e0a7-4ddc-8c25-c187d3e4f338
                nombre: Emily Quintero
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties: {}
                example: *ref_1
  /api/Client:
    get:
      tags:
        - Client
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties: {}
                example: null
    post:
      tags:
        - Client
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: {}
              example: &ref_2
                uuid: 520d1ddd-e0a7-4ddc-8c25-c187d3e4f338
                nombre: Esteban Quintero
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties: {}
                example: *ref_2
  /api/Client/:uuid:
    put:
      tags:
        - Client
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: {}
              example: &ref_3
                uuid: 520d1ddd-e0a7-4ddc-8c25-c187d3e4f338
                nombre: Emily Quintero
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties: {}
                example: *ref_3
components:
  parameters: {}
  definitions: {}
  schemas:
    User:
      type: object
      properties:
        uuid:
          type: string
          required: true
          description: identificador universal unico para la tabal usuario
          example: '3973'
        nombre:
          type: string
          required: true
          description: nombre de usuario
          example: '3973'
    Client:
      type: object
      properties:
        uuid:
          type: string
          required: true
          description: identificador universal unico para la tabal cliente
          example: '3973'
        nombre:
          type: string
          required: true
          description: nombre del clinete
          example: '3973'
  tags:
    - User
    - Client
