openapi: 3.0.0
info:
  title: lambda-express-sequelize
  description: documentación lambda-express-sequelize
  version: 1.0.0
  servers:
    - http://localhost:4000
paths:
  /api/User:
    get:
      tags:
        - User
      summary: null
      description: null
      responses:
        '200':
          description: null
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/User'
    post:
      tags:
        - User
      summary: null
      description: null
      responses:
        '200':
          description: null
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/User'
  /api/Client:
    get:
      tags:
        - Client
      summary: null
      description: null
      responses:
        '200':
          description: null
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/Client'
    post:
      tags:
        - Client
      summary: null
      description: null
      responses:
        '200':
          description: null
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/Client'
components:
  parameters: {}
  definitions: {}
  schemas:
    User:
      type: object
      properties:
        uuid:
          type: string
          required: true
          description: identificador universal unico para la tabal usuario
          example: '3973'
        nombre:
          type: string
          required: true
          description: nombre de usuario
          example: '3973'
    Client:
      type: object
      properties:
        uuid:
          type: string
          required: true
          description: identificador universal unico para la tabal cliente
          example: '3973'
        nombre:
          type: string
          required: true
          description: nombre del clinete
          example: '3973'
  tags:
    - name: sequelize
      description: null
    - name: options
      description: null
    - name: associations
      description: null
    - name: underscored
      description: null
    - name: tableName
      description: null
    - name: _schema
      description: null
    - name: _schemaDelimiter
      description: null
    - name: rawAttributes
      description: null
    - name: _indexes
      description: null
    - name: primaryKeys
      description: null
    - name: _readOnlyAttributes
      description: null
    - name: _timestampAttributes
      description: null
    - name: _hasReadOnlyAttributes
      description: null
    - name: _dataTypeChanges
      description: null
    - name: _dataTypeSanitizers
      description: null
    - name: _hasBooleanAttributes
      description: null
    - name: _hasDateAttributes
      description: null
    - name: _jsonAttributes
      description: null
    - name: _virtualAttributes
      description: null
    - name: _defaultValues
      description: null
    - name: fieldRawAttributesMap
      description: null
    - name: uniqueKeys
      description: null
    - name: fieldAttributeMap
      description: null
    - name: _hasJsonAttributes
      description: null
    - name: _hasVirtualAttributes
      description: null
    - name: _hasDefaultValues
      description: null
    - name: tableAttributes
      description: null
    - name: primaryKeyAttributes
      description: null
    - name: primaryKeyAttribute
      description: null
    - name: primaryKeyField
      description: null
    - name: _hasPrimaryKeys
      description: null
    - name: _isPrimaryKey
      description: null
    - name: _attributeManipulation
      description: null
    - name: autoIncrementAttribute
      description: null
    - name: _scope
      description: null
    - name: _scopeNames
      description: null
